"""add is_moderator column

Revision ID: 55a34bc2eae9
Revises: e1b7d6eaa4f2
Create Date: 2025-08-21 18:15:27.108163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a34bc2eae9'
down_revision = 'e1b7d6eaa4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moderator', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_moderator')

    # ### end Alembic commands ###
