"""create poems and likes tables

Revision ID: 7049f8cc0b7f
Revises: 1070ff61a5bc
Create Date: 2025-09-11 13:16:39.330189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7049f8cc0b7f'
down_revision = '1070ff61a5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_followers_followed_username'))
        batch_op.drop_index(batch_op.f('idx_followers_username'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_recipient'))
        batch_op.drop_index(batch_op.f('idx_notifications_timestamp'))

    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_poems_created_at'))
        batch_op.drop_index(batch_op.f('idx_poems_username'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_poems_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_poems_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notifications_timestamp'), [sa.literal_column('timestamp DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_recipient'), ['recipient'], unique=False)

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_followers_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_followers_followed_username'), ['followed_username'], unique=False)

    # ### end Alembic commands ###
