"""add anonymous messaging support

Revision ID: a6a462a360b9
Revises: eac6bb1a3b44
Create Date: 2025-08-04 21:20:53.130433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a462a360b9'
down_revision = 'eac6bb1a3b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_anonymous_messages', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allow_anonymous_messages')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###
